### ISSUE TITLE
Using 0 to trun on/off all relays doesn't always work

### ISSUE THREAD

**Issue by jht001** [bmrzycki/lcus_relay#1]
I'm using the the 2 relay usb board.  I'm power cycling +5 and +12 volts for a SATA disk.
I've noticed that while usually using 0 for all relays works as intended, it doesn't always work correctly, sometimes it only turns on only one relay.  Maybe a timing issue somewhere?

**Comment by bmrzycki** [comment]
Hello @jht001, it's entirely possible. While I've never encountered it I can hardly say I've done exhaustive on/off testing of these devices over a large number of cycles.

The communication mechanism to the relay is via serial and turning on both relays requires two separate commands.  I can't send one command that means all relays and instead have to send two. It's possible the device buffer can't keep up. These are inexpensive devices and I did have to do a bit of massaging with timings for the first release for my own use.

I'm assuming your code looks something like:
```
# ...
import lcus_relay
# ...
r = lcus_relay.Relay(port=port)
# ...
r.on(0)
```

Could you try the following change to see if it helps?

```
# ...
import lcus_relay
import time
# ...
r = lcus_relay.Relay(port=port)
# ...
r.on(1)
time.sleep(100 / 1000.0)  # 100 ms delay
r.on(2)
```
I recommend testing this while the SATA disk is not connected to not stress the disk with excessive power cycling.

If that does work relaiably can you shorten the delay a bit to as low as about 10 or 5 ms and see if it's still reliable? If so I can add that to the `_send()` method when `relay=0`.

**Comment by jht001** [comment]
Thanks for the quick reply.  I will try that.  I also ordered a DPDT USB relay from Numato Labs that would eliminate the possibility of the relays being out of sync for my application.

Currently I'm doing:
r.on(0)
r.status() 
I check both relays are on, if not, turn them off and try again

Not optimal since it leaves the device with only 1 of its supply voltages momentarily.

I'll try to run some tests to see how frequently it occurs and with various delay times.

Thanks.

**Comment by bmrzycki** [comment]
Hi @jht001, a DPDT device definitely makes more sense for your application both for out-of-sync issues as well as lag time between throwing both relays on.

The `r.status()` is also not a great answer: I have to read state twice to reliably debounce the result. That combined with the overhead of sending `r.on(N)` to the off device means you'll have an unstable power state for several 10s of milliseconds and may shorten the life of your drive.

I'm curious to know the results of your tests.  Thanks for helping!

**Comment by jht001** [comment]
I changed from using zero to doing 1 delay(100ms) 2 and the issue seems to have gone away.
Don't have time to do more testing at the moment, thanks for the suggestion!

**Comment by bmrzycki** [comment]
Great news! I may add a feature in the future to add a delay during class instantiation such as
`lcus_relay.Relay(port=port, multi_delay=100)` to make this a little nicer for users like you in the future.

Closing as explained: if you disagree please reopen. Take care!
